"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const link_vue_vue_type_script_setup_true_lang = require("./src/link.vue.js");
const install = require("../packages/utils/vue/install.js");
const link = require("./src/link.js");
const RaLink = install.withInstall(link_vue_vue_type_script_setup_true_lang);
exports.linkEmits = link.linkEmits;
exports.linkProps = link.linkProps;
exports.RaLink = RaLink;
exports.default = RaLink;
