"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const icon_vue_vue_type_script_setup_true_lang = require("./src/icon.vue.js");
const install = require("../packages/utils/vue/install.js");
const icon = require("./src/icon.js");
const RaIcon = install.withInstall(icon_vue_vue_type_script_setup_true_lang);
exports.iconEmits = icon.iconEmits;
exports.iconProps = icon.iconProps;
exports.RaIcon = RaIcon;
exports.default = RaIcon;
