"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const install = require("../packages/utils/vue/install.js");
const mask_vue_vue_type_script_setup_true_lang = require("./src/mask.vue.js");
const mask = require("./src/mask.js");
const RaMask = install.withInstall(mask_vue_vue_type_script_setup_true_lang);
exports.maskEmits = mask.maskEmits;
exports.maskProps = mask.maskProps;
exports.RaMask = RaMask;
exports.default = RaMask;
