"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
require("./src/function.js");
const install = require("../packages/utils/vue/install.js");
const message = require("./src/message.js");
const instance = require("./src/instance.js");
const RaMessage = install.withInstallFunction(instance, "$message");
exports.messageProps = message.messageProps;
exports.messageTheme = message.messageTheme;
exports.RaMessage = RaMessage;
exports.default = RaMessage;
